default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: app_development
  host: <%= ENV.fetch("DATABASE_HOST", "db") %>
  username: <%= ENV.fetch("DATABASE_USER", "myapp_user") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD", "password") %>

test:
  <<: *default
  database: app_test
  host: <%= ENV.fetch("DATABASE_HOST", "db") %>
  username: <%= ENV.fetch("DATABASE_USER", "myapp_user") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD", "password") %>

# Preview環境用（新規追加）
staging:
  <<: *default
  database: gamut_cut_db_preview  # preview用のDB名
  url: <%= ENV['DATABASE_URL'] %>

# Production環境用
production:
  <<: *default
  database: gamut_cut_db  # production用のDB名
  url: <%= ENV['DATABASE_URL'] %>